server:
  port: 80
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:    
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  mail:
      host: smtp.gmail.com
      port: 587
      username: tkddnjs1023@gmail.com
      password: zwqx1023!
      properties:
        mail.smtp.auth: true
        mail.smtp.starttls.enable: true
      
  datasource:
    #driver-class-name: oracle.jdbc.driver.OracleDriver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #url: jdbc:oracle:thin:@127.0.0.1:1521:XE
    #url: jdbc:oracle:thin:@192.168.0.235:1521:XE
    url: jdbc:log4jdbc:oracle:thin:@192.168.0.235:1521:XE
    #url: jdbc:log4jdbc:oracle:thin:@127.0.0.1:1521:XE
    username: icia
    password: 1234
    


  jackson:
    serialization:
      fail-on-empty-beans: false
      
mybatis:
  mapper-locations:
  - mappers/*.xml
  

  

