server:
  port: 80
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:XE
    #url: jdbc:oracle:thin:@192.168.0.235:1521:XE
    username: icia
    password: 1234

  jackson:
    serialization:
      fail-on-empty-beans: false
      
mybatis:
  mapper-locations:
  - mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

